apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversao-temperatura
spec:
  replicas: 2
  selector:
    matchLabels:
      app: conversao-temp
  template:
    metadata:
      labels:
        app: conversao-temp
    spec:
      containers:
      - name: conversao-temperatura
        image: wallissonbrk/conversao-temperatura:v2
--- 
apiVersion: v1 
kind: Service
metadata:
  name: conversao-temperatura
spec:
  selector:
    app: conversao-temp
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30000
  type: NodePort